Introduces monaco-editor
geostyler/geostyler pull request #1395
Opened 2021-03-16 09:52 UTC by KaiVolland

## Description

This replaces editor used for the `CodeEditor` component.
[Code-Mirror](https://codemirror.net/) is replaced with [Monaco-Editor](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults) wrapped by [`@monaco-editor/react`](https://www.npmjs.com/package/@monaco-editor/react).

![monaco-screenshot](https://user-images.githubusercontent.com/1849416/111288326-59f41a80-8644-11eb-839c-8b8b427bc987.png)

The monaco-editor comes with tons of extra features and optional plugins. For example, we can use the new geostyler-style JSON schema (https://github.com/geostyler/geostyler-style/pull/154) to validate, document and autocomplete the entered geostyler-style.

The old code-mirror editor is not removed completly but moved to the `Legacy` folder in components.

As this PR relies on https://github.com/geostyler/geostyler-style/pull/154 (and a corresponding release) it is currently in draft mode but can be reviewed allready.

## Pull request type

- [ ] Bugfix
- [x] Feature
- [x] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [BSD 2-Clause License](https://github.com/geostyler/geostyler/blob/master/)
- [x] I have followed the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

2021-03-16 13:24 UTC, KaiVolland commented
Sadly i had to remove a lot of tests. They all try to access methods of the component which are not exposed anymore as i transformed the class component into a function component.

2021-03-16 16:21 UTC, dnlkoch approved these changes

2021-03-16 16:21 UTC, dnlkoch commented on src/Component/CodeEditor/CodeEditor.tsx
> +const MODELPATH = 'geostlyer.json';  // associate with our model
```suggestion
const MODELPATH = 'geostyler.json';  // associate with our model
```

2021-03-16 16:21 UTC, dnlkoch commented on src/Component/CodeEditor/CodeEditor.tsx
> +  let editTimeout: any;
```suggestion
  let editTimeout: number;
```

2021-03-16 16:21 UTC, dnlkoch commented on src/Component/CodeEditor/CodeEditor.tsx
> +          style={{ width: 300 }}
Not related to this PR in particular, but style should be moved to the style definition.

2021-03-16 16:21 UTC, dnlkoch commented on src/Component/CodeEditor/CodeEditor.tsx
> +          !showCopyButton ? null :
```suggestion
          showCopyButton &&
```

2021-03-16 16:21 UTC, dnlkoch commented on src/Component/CodeEditor/CodeEditor.tsx
> +          !showSaveButton ? null :
```suggestion
          showSaveButton &&
```

2021-03-17 08:44 UTC, KaiVolland commented
Thanks for the review @dnlkoch

2021-03-17 08:53 UTC, jansule requested changes

2021-03-17 08:53 UTC, jansule commented on src/hook/UsePrevious.tsx
> +export const usePrevious = <T extends unknown>(value: T): T | undefined => {
Minor: Some explanatory comments would be nice.

2021-03-17 08:53 UTC, jansule commented on src/hook/UsePrevious.tsx
> +import { useEffect, useRef } from 'react';
Could you please add a license header?

2021-03-17 09:02 UTC, jansule approved these changes
Nice work @KaiVolland! This is ready to merge now.

2021-03-17 09:14 UTC, merged