Harmonization
geostyler/geostyler pull request #1998
Opened 2022-11-29 15:07 UTC by jansule

## Description

This prepares the `<CardStyle />` components and its supcomponents for making use of the `GeoStylerContext`. The overall goal will be to harmonize the properties between `<Style/>` and `<CardStyle/>` in order to be able to use both components under a common wrapper component.

The actual use of `GeoStylerContext` will be done in a separate PR.

## Related issues or pull requests

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [x] Yes
- [ ] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [BSD 2-Clause License](https://github.com/geostyler/geostyler/blob/main/)
- [x] I have followed the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/main/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/geostyler/geostyler/blob/main/CODE_OF_CONDUCT.md)
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

2023-02-09 09:10 UTC, KaiVolland requested changes
Very nice. But i guess we cann improve the typing of the renderer a bit more.

2023-02-09 09:10 UTC, KaiVolland commented on src/Component/Renderer/Renderer/Renderer.tsx
> +  height?: number;
I think you could reuse the props of `OlRenderer` and `SLDRenderer` here.

2023-02-16 16:13 UTC, jansule commented on src/Component/RuleCard/RuleCard.example.md
> +class RuleCardExample extends React.Component {
done

2023-02-16 16:13 UTC, jansule commented on src/Component/RuleTable/RuleTable.tsx
> +  oLRendererProps?: Partial<OlRendererProps>;
will keep it as is, since this will be subject of a subsequent PR anyways.

2023-02-16 16:13 UTC, jansule commented on src/context/GeoStylerContext/GeoStylerContext.tsx
> +    height?: number;
done

2023-02-17 09:54 UTC, KaiVolland approved these changes

2023-02-17 10:08 UTC, merged