Fix translation
geostyler/geostyler pull request #2062
Opened 2023-01-18 14:33 UTC by FritzHoing

## Description
- Proposed imports need to be imported as default for the localize wrapper to work as intended.
- Adds missing dynamic translation to the ScaleDenominator files.

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

2023-01-18 15:14 UTC, KaiVolland reviewed
Nice.
But as you're refactoring it already we might consider to remove the `label` prop completly as it is part of the locale.
This would leed to a breaking change but we are doing a bigger refactoring with #1998 anyway so that should be no problem.

2023-01-18 15:14 UTC, KaiVolland commented on src/Component/ScaleDenominator/MaxScaleDenominator.tsx
> +  label = locale.maxScaleDenominatorLabelText,
I think the extra `label` prop should be removed here and we should use `locale.maxScaleDenominatorLabelText` in the JSX element instead.

2023-01-18 15:14 UTC, KaiVolland commented on src/Component/ScaleDenominator/MaxScaleDenominator.tsx
> +      {...formItemLayout} >
```suggestion
      {...formItemLayout}
  >
```

2023-01-18 15:14 UTC, KaiVolland commented on src/Component/ScaleDenominator/MinScaleDenominator.tsx
> +  label = locale.minScaleDenominatorLabelText,
see above

2023-01-18 15:14 UTC, KaiVolland commented on src/Component/ScaleDenominator/MinScaleDenominator.tsx
> +      {...formItemLayout}>
```suggestion
      {...formItemLayout}
  >
```

2023-01-19 15:37 UTC, FritzHoing commented
Thank you for the review @KaiVolland !

2023-01-19 15:48 UTC, KaiVolland approved these changes

2023-01-20 10:49 UTC, jansule requested changes
Very nice @FritzHoing. Just one remark

2023-01-20 10:49 UTC, jansule commented on src/Component/ScaleDenominator/MinScaleDenominator.tsx
> +// export default MinScaleDenominator;
Minor: Please remove this line

2023-01-20 10:55 UTC, FritzHoing commented on src/Component/ScaleDenominator/MinScaleDenominator.tsx
> +// export default MinScaleDenominator;
Good catch! Thank you @jansule

2023-01-20 11:50 UTC, jansule approved these changes

2023-01-31 07:52 UTC, merged